"""add_design_json_to_agent_sessions

Revision ID: e26c2ab6dc8f
Revises: 0b08ccd7da20
Create Date: 2026-07-29 17:23:45.300427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26c2ab6dc8f'
down_revision: Union[str, Sequence[str], None] = '0b08ccd7da20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_sessions', sa.Column('design_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_sessions', 'design_json')
    # ### end Alembic commands ###
